package app

import (
	"context"
	_ "courses/docs" // docs is generated by Swag CLI, you have to import it.
	authHttp "courses/internal/auth/delivery/http"
	authPostgres "courses/internal/auth/repository/postgres"
	authUseCase "courses/internal/auth/usecase"
	"courses/internal/config"
	managementHttp "courses/internal/management/delivery/http"
	managementPostgres "courses/internal/management/repository/postgres"
	managementUseCase "courses/internal/management/usecase"
	"courses/pkg/auth/jwtImpl"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"time"

	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

// Run ...
func Run(confpath string) error {
	conf, err := config.Init(confpath)
	if err != nil {
		fmt.Println(err)
		return err
	}

	rout := gin.Default()

	jwtToken, err := jwtImpl.NewJWT(conf.JWT.SigningKey, int64(conf.JWT.ExpiredDuration))

	if err != nil {
		fmt.Println(err)
		return err
	}
	// urlExample := "postgres://username:password@localhost:5432/database_name"
	dburl := fmt.Sprintf("%s://%s:%s@%s:%s/%s", conf.Database.DBMS, conf.Database.Username, conf.Database.Password, conf.Database.Host, conf.Database.Port, conf.Database.Dbname)

	// dburl = ""
	// dburl = os.Getenv("DATABASE_URL")
	// strings.Split(dburl, ":")

	fmt.Println("db url = ", dburl)

	dbAuthRepo := authPostgres.NewDatabase(dburl)
	fmt.Println("first db success")
	userAuthRepo := authPostgres.NewUserRepository(dbAuthRepo)
	userAuthUseCase := authUseCase.NewAuthUseCase(userAuthRepo, jwtToken)
	userAuthHandler := authHttp.NewUserHandler(userAuthUseCase)
	safeGroup := userAuthHandler.RegisterUser("auth", rout)

	dbBusinessRepo := managementPostgres.NewDatabase(dburl)
	fmt.Println("second db success")
	userRepo := managementPostgres.NewUserRepository(dbBusinessRepo)
	UserUseCase := managementUseCase.NewUserUseCase(userRepo)
	userHandler := managementHttp.NewUserHandler(UserUseCase)
	userHandler.RegisterUser("business", safeGroup)

	rout.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// port := os.Getenv("PORT")
	port := conf.Http.Port
	if port == "" {
		port = "3000"
	}

	// conf.Http.Port = ":" + port
	fmt.Println("port ===>", port)
	httpServer := &http.Server{
		Addr:           ":" + port,
		Handler:        rout,
		ReadTimeout:    conf.Http.ReadTimeout,
		WriteTimeout:   conf.Http.WriteTimeout,
		MaxHeaderBytes: conf.Http.MaxHeaderMegabytes << 20,
	}

	go func() {
		if err := httpServer.ListenAndServe(); err != nil {
			log.Fatalf("Failed to listen and serve: %+v", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, os.Interrupt, os.Interrupt)

	<-quit

	fmt.Println("Shutting down the Server ...")
	ctx, shutdown := context.WithTimeout(context.Background(), 5*time.Second)

	defer func() {
		fmt.Println("The Server stopped .. Zzzz ..")
		fmt.Println("closing auth db error =>", dbAuthRepo.Close())
		// fmt.Println("closing business db error => ", dbBusinessRepo.Close())
		shutdown()
	}()

	fmt.Println("Server Exiting")

	return httpServer.Shutdown(ctx)
}
